---

- name: Install MySQL server
  yum: pkg=mysql-server
       state=present

- name: Start MySQL server
  service: name=mysqld
           state=started
           enabled=yes

- name: Install MySQL client tools
  yum: pkg=mysql
       state=present

- name: Install MySQL-python
  yum: pkg=MySQL-python
       state=installed

- name: Configure root user
  mysql_user: name=root
              password={{ mysql_root_password }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
    - 127.0.0.1
    - localhost

- name: Setup my.cnf
  template: src=my.cnf.j2
            dest=/root/.my.cnf
            owner=root
            mode=0600

- name: Remove test database
  mysql_db: name=test
            state=absent

- name: Install MySQL development package
  yum: pkg=mysql-devel
       state=installed
