- name: Check for rbenv
  stat: path=/home/app/.rbenv
  register: rbenv

- name: Install rbenv
  become: true
  become_user: app
  git: repo=git://github.com/sstephenson/rbenv.git
       dest=/home/app/.rbenv
       accept_hostkey=yes
  when: rbenv.stat.exists == false

- name: Check for ruby-build
  stat: path=/home/app/.rbenv/plugins/ruby-build
  register: rubybuild

- name: Install ruby-build
  become: true
  become_user: app
  git: repo=git://github.com/sstephenson/ruby-build.git
       dest=/home/app/.rbenv/plugins/ruby-build
       accept_hostkey=yes
  when: rubybuild.stat.exists == false

- name: Check for rbenv-vars
  stat: path=/home/app/.rbenv/plugins/rbenv-vars
  register: rbenvvars

- name: Install rbenv-vars
  become: true
  become_user: app
  git: repo=git://github.com/sstephenson/rbenv-vars.git
       dest=/home/app/.rbenv/plugins/rbenv-vars
       accept_hostkey=yes
  when: rbenvvars.stat.exists == false

- name: Install rbenv loader
  copy: src=rbenv.sh
        dest=/etc/profile.d/rbenv.sh

- name: Install Ruby dependencies
  yum: pkg={{ item }}
       state=present
  with_items:
    - gcc
    - libffi-devel    
    - libyaml-devel
    - make
    - openssl-devel
    - readline-devel
    - zlib-devel

- name: Install Ruby 2.2.1
  command: su - app -c "rbenv install 2.2.1"
  args:
    creates: /home/app/.rbenv/versions/2.2.1

- name: Set global Ruby
  become: true
  become_user: app
  copy: content=2.2.1
        dest=/home/app/.rbenv/version

- name: Install patch command for Bundler
  yum: pkg=patch
       state=present

- name: Install Bundler
  command: su - app -c "gem install bundler"
  args:
    creates: /home/app/.rbenv/versions/2.2.1/bin/bundle
